config/routes.rb
Rails.application.routes.draw do

  get 'home/meetups'

  get 'home/jobs'

  get 'home/about'

  get 'home/contests'

  get 'home/blog'

  resources :users do
    get 'following' => 'users#following'
    get 'followers' => 'users#followers'
    get 'analytics' => 'users#analytics'
    get 'activity' => 'users#activity'
    post 'get_quote' => 'mail#get_quote'
    resources :projects, :except => [:new]
    resources :reviews, :only => [:index, :create]
    resources :replies, :only => [:create, :update]
    resources :bookings, :only => [:index, :create, :update]
  end

  resources :photos do
    get 'fullsize' => 'photos#fullsize'
    resources :comments, :only => [:create]
  end

  resources :photo_contents, :only => [:create]
  resources :search, :only => [:index]

  put '/users/:user_id/replies/:id', :to => 'replies#update', :as => 'update_reply'
  put '/users/:id/bookings', :to => 'bookings#update', :as => 'update_booking'
  post '/upload_avatar' => 'users#upload_avatar'
  post '/upload_hero_bg' => 'users#upload_hero_bg'
  post '/add_project' => 'projects#add_project'
  post '/add_follow' => 'users#add_follow'
  delete '/unfollow' => 'users#unfollow'
  post '/like' => 'photos#like'
  delete '/unlike' => 'photos#unlike'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  
  root :to =>'photos#index'

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :user
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
	require 'will_paginate'
	before_action :require_user

	def index
		@user = User.friendly.find(params[:user_id])
		@bookings = Booking.where("user_id = ? OR requestor_id = ?", @user.id, @user.id).order(:created_at => :desc)
		@description = @user.description.truncate(150)
		@title = "#{@user.firstname.titleize} #{@user.lastname.titleize} - Photographer Reviews"
		@og_image = @user.avatar.present? ? request.base_url + @user.avatar_url : request.base_url + '/assets/user_profiles/default.png'
		redirect_to root_path if @user != current_user
	end

	def create
    @user = User.friendly.find(params[:user_id])
    date = Date.strptime(params[:date], '%m/%d/%Y')
    if @user.id != current_user.id
	    Booking.create(:user_id => @user.id, :requestor_id => current_user.id, :date_booked => date, :accepted_status => nil)
	    Activity.create(:user_id => @user.id, :activity_type => 'booking', :from => current_user.id)
	    redirect_to user_bookings_path(current_user)
    end		
	end

	def update
		booking = Booking.find(params[:booking_id])
		booking.accepted_status = params[:accepted_status]
		if booking.save
			redirect_to :back
		end
	end

end

app/views/bookings/index.html.erb
<%= render "shared/nav" %>
<%= render "shared/partial_hero__portfolio" %>
<div class="container">

	<div class="request-table" data-example-id="hoverable-table"> 
		<table class="table table-hover"> 
			<thead> 
				<tr> 
					<th>#</th>
					<th>First Name</th> 
					<th>Last Name</th> 
					<th>Booking Type</th>
					<th>Status</th>
					<th>Date requested</th>
				</tr> 
			</thead> 
				<tbody>
					<% @bookings.each do |booking| %>
					<tr> 
						<th scope="row">
						<% if booking.user_id == @user.id %>
							<a class="url" rel="contact" title="" href="<%= user_reviews_path(User.find(booking.requestor_id)) %>">
							<% if User.find(booking.requestor_id).avatar.present? %>
									<%= image_tag User.find(booking.requestor_id).avatar_url(:thumb), alt: "#{User.find(booking.requestor_id).firstname.titleize} #{User.find(booking.requestor_id).lastname.titleize}", :id => "avatar", :style => "height: 32px; width: 32px; margin-top: -5px;" , class: "img-circle" %>
								<% else %>	
									<span class="circle"><span><%= User.find(booking.requestor_id).firstname[0].upcase %></span></span>
								<% end %>
							</a>
						<% else %>
							<a class="url" rel="contact" title="" href="<%= user_reviews_path(User.find(booking.user_id)) %>">
							<% if User.find(booking.user_id).avatar.present? %>
									<%= image_tag User.find(booking.user_id).avatar_url(:thumb), alt: "#{User.find(booking.user_id).firstname.titleize} #{User.find(booking.user_id).lastname.titleize}", :id => "avatar", :style => "height: 32px; width: 32px; margin-top: -5px;" , class: "img-circle" %>
								<% else %>	
									<span class="circle"><span><%= User.find(booking.user_id).firstname[0].upcase %></span></span>
								<% end %>
							</a>						
						<% end %>
						</th>  
						<td><%= booking.requestor_id == @user.id ? User.find(booking.user_id).firstname.titleize : User.find(booking.requestor_id).firstname.titleize %></td> 
						<td><%= booking.requestor_id == @user.id ? User.find(booking.user_id).lastname.titleize : User.find(booking.requestor_id).lastname.titleize %></td>
						<td><%= booking.requestor_id == @user.id ? "Sent" : "Received" %> 
						<td>
							<% if booking.accepted_status == nil && booking.user_id == @user.id %>
									<span style="font-style: italic;">Pending: </span>
									<span><%= link_to 'Accept', update_booking_path(current_user, :booking_id => booking.id, :accepted_status => true), :method => :put %></span>
									<span><%= link_to 'Reject', update_booking_path(current_user, :booking_id => booking.id, :accepted_status => false), :method => :put %></span>
							<% elsif booking.accepted_status %>
								Accepted
							<% elsif booking.accepted_status == nil %>
								Pending
							<% else %>
								Rejected
							<% end %>
						</td>
						<td><%= booking.date_booked.strftime("%b %d, %Y") %></td> 
					</tr>
					<% end %>
				</tbody> 
		</table> 
	</div>	

</div>