config/routes.rb
Rails.application.routes.draw do

  get 'home/meetups'

  get 'home/jobs'

  get 'home/about'

  get 'home/contests'

  get 'home/blog'

  resources :users do
    get 'following' => 'users#following'
    get 'followers' => 'users#followers'
    get 'analytics' => 'users#analytics'
    get 'activity' => 'users#activity'
    post 'get_quote' => 'mail#get_quote'
    resources :projects, :except => [:new]
    resources :reviews, :only => [:index, :create]
    resources :replies, :only => [:create, :update]
    resources :bookings, :only => [:index, :create, :update]
  end

  resources :photos do
    get 'fullsize' => 'photos#fullsize'
    resources :comments, :only => [:create]
  end

  resources :photo_contents, :only => [:create]
  resources :search, :only => [:index]

  put '/users/:user_id/replies/:id', :to => 'replies#update', :as => 'update_reply'
  put '/users/:id/bookings', :to => 'bookings#update', :as => 'update_booking'
  post '/upload_avatar' => 'users#upload_avatar'
  post '/upload_hero_bg' => 'users#upload_hero_bg'
  post '/add_project' => 'projects#add_project'
  post '/add_follow' => 'users#add_follow'
  delete '/unfollow' => 'users#unfollow'
  post '/like' => 'photos#like'
  delete '/unlike' => 'photos#unlike'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  
  root :to =>'photos#index'

end

app/views/shared/_nav.html.erb
          <nav class="navbar navbar-fixed-top">
            <div class="container">

              <div class="navbar-header">
                <button type="button" class="navbar-toggle navbar-toggle__left">
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">
                  <%= image_tag("site_assets/logo.png", alt: "Photocray Logo") %> 
                </a>
              </div>

              <div id="meta" class="activity">
                 <ul class="nav navbar-nav navbar-right">
                     
                    <li class="search hidden-xs"> 
                      <a href="#" id="search-btn"> 
                        <i class="fa fa-lg fa-search"></i>
                      </a>
                      <div class="search-form search-hidden">
                        <div class="form-group">
                          <%= form_tag url_for(controller: "search", action: "index"), method: "get" do %>
                            <div class="input-holder">
                              <%= button_tag '<i class="fa fa-search"></i>'.html_safe, name: nil %>
                              <%= search_field_tag :query, params[:query], class: 'form-control search-field' %>
                            </div>
                          <% end %>  
                        </div>                       
                      </div>
                    </li>
                  <% if current_user %>
                    <li class="notify dropdown dropdown-hover"> 
                      <a href="#"> 
                        <i class="fa fa-lg fa-bell"><span class="notify-dot is-active"></span></i>
                        
                      </a>
                      <ul class="dropdown-menu" role="menu">
                      <% if user_activities(current_user).length > 4 %>
                        <div style="height: 232px; overflow: auto">
                      <% end %>
                          <% user_activities(current_user).each do |activity| %>
                            <% if activity.activity_type == 'like' %>
                              <li class="like">
                                <i class="notify-icon color-danger fa fa-heart"></i>
                                <div class="notify-info">
                                  <span class="vcard">
                                    <a class="url" rel="contact" href="<%= user_path(activity.from) %>"><%= User.find(activity.from).firstname.titleize %></a>
                                  </span>
                                  <span>liked your</span>
                                  <a href="<%= photo_path(activity.activity_id) %>">photo</a>
                                  <em class="time"><%= time_ago_in_words(activity.created_at) %></em>
                                </div>
                              </li>
                            <% elsif activity.activity_type == 'follower' %>
                              <li class="follow">
                                <i class="notify-icon fa fa-child"></i>
                                <div class="notify-info">
                                  <span class="vcard">
                                    <a class="url" rel="contact" href="<%= user_path(activity.from) %>"><%= User.find(activity.from).firstname.titleize %></a>
                                  </span>
                                  <span>followed</span>
                                  <a href="<%= user_followers_path(current_user) %>">You</a>
                                  <em class="time"><%= time_ago_in_words(activity.created_at) %></em>
                                </div>
                              </li>
                            <% elsif activity.activity_type == 'comment' %>
                              <li class="comment">
                                <i class="notify-icon fa fa-comment"></i>
                                <div class="notify-info">
                                  <span class="vcard">
                                    <a class="url" rel="contact" href="<%= user_path(activity.from) %>"><%= User.find(activity.from).firstname.titleize %></a>
                                  </span>
                                  <span>commented on your</span>
                                  <a href="<%= photo_path(activity.activity_id) %>">Photo</a>
                                  <em class="time"><%= time_ago_in_words(activity.created_at) %></em>
                                </div>
                              </li>
                            <% elsif activity.activity_type == 'review' %>
                              <li class="mention">
                                <i class="notify-icon fa fa-pencil-square-o"></i>
                                <div class="notify-info">
                                  <span class="vcard">
                                    <a class="url" rel="contact" href="<%= user_path(activity.from) %>"><%= User.find(activity.from).firstname.titleize %></a>
                                  </span>
                                  <span>reviewed</span>
                                  <a href="<%= user_reviews_path(current_user) %>">You</a>
                                  <em class="time"><%= time_ago_in_words(activity.created_at) %></em>
                                </div>
                              </li>
                            <% elsif activity.activity_type == 'booking' %>
                              <li class="mention">
                                <i class="notify-icon color-success fa fa-check"></i>
                                <div class="notify-info">
                                  <span class="vcard">
                                    <a class="url" rel="contact" href="<%= user_path(activity.from) %>"><%= User.find(activity.from).firstname.titleize %></a>
                                  </span>
                                  <span>booked</span>
                                  <a href="<%= user_bookings_path(current_user) %>">You</a>
                                  <em class="time"><%= time_ago_in_words(activity.created_at) %></em>
                                </div>
                              </li>
                            <% end %>
                          <% end %>
                      <% if user_activities(current_user).length > 4 %>
                        </div>
                      <% end %>
                        <li class="more"><a href="<%= user_analytics_path(current_user) %>">See All Incoming Activity</a></li>
                      </ul>

                    </li>
                  <% end %>
                  <% if current_user %>  
                    <li class="profile dropdown dropdown-hover">
                      <a href="<%= current_user.is_photographer ? user_path(current_user) : user_reviews_path(current_user) %>">
                      <% if current_user.avatar.present? %>
                        <%= image_tag current_user.avatar_url(:thumb), alt: "#{current_user.firstname.titleize} #{current_user.lastname.titleize}", :id => "avatar", :style => "height: 32px; width: 32px; margin-top: -5px;" , class: "img-circle" %>
                      <% else %>  
                        <div id="avatar-nav">
                          <%= image_tag("user_profiles/default-avatar.jpg", alt: "avatar", :id => "avatar-image-nav", :style => "height: 32px; width: 32px; margin-top: -5px;", :class => "img-circle") %>
                          <p id="avatar-text-nav"><%= current_user.firstname[0].upcase %></p>
                        </div>
                      <% end %>                      
                      </a>
                      <ul class="dropdown-menu" role="menu" style="top:51px">
                        <li><a href="<%= user_path(current_user) %>">Profile</a></li>
                        <li><a href="<%= user_following_path(current_user) %>">Friends</a></li>
                        <li><a href="<%= edit_user_path(current_user) %>">Account Settings</a></li>
                        <li><a href="<%= user_analytics_path(current_user) %>">Stats</a></li>
                        <li><a href="<%= logout_path %>">Sign Out</a></li>
                      </ul>
                    </li>
                  <% end %>
                  <% if !current_user %>
                    <li><a href="<%= new_user_path %>">Login</a></li>
                  <% end %>                  
                 </ul>
              </div>

              <div id="navigation" class="offcanvas">
                <ul class="nav navbar-nav">
                  <li class="search visible-xs-block"> 
                    <div class="search-form">
                      <div class="form-group">
                        <div class="input-holder">
                          <button type="submit"> <i class="fa fa-search"></i> </button>
                          <input type="search" class="form-control search-field" placeholder="Search something..." /> 
                        </div>
                      </div> 
                    </div>                  
                  </li>
                  <li class="<%= 'active' if is_photos_page? %>"><a href="<%= root_path %>">Photos</a></li>
                  <li class="<%= 'active' if is_photographers_page? %>"><a href="<%= users_path %>">Photographers</a></li>
                  <% if false %>
                    <li class="<%= 'active' if is_meetups_page? %>"><a href="<%= home_meetups_path %>">Meetups</a></li>
                    <li class="<%= 'active' if is_jobs_page? %>"><a href="<%= home_jobs_path %>">Jobs</a></li>
                    <li class="dropdown dropdown-hover">
                      <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"> 
                        <span class="icon-dot"></span> 
                        <span class="icon-dot"></span> 
                        <span class="icon-dot"></span> 
                      </a>
                      <ul class="dropdown-menu" role="menu">
                        <li class="<%= 'active' if is_about_page? %>"><a href="<%= home_about_path %>">About</a></li>
                        <li class="<%= 'active' if is_contests_page? %>"><a href="<%= home_contests_path %>">Contests</a></li>
                        <li class="<%= 'active' if is_blog_page? %>"><a href="<%= home_blog_path %>">Blog</a></li>
                      </ul>
                    </li>
                  <% end %>
                </ul>
              </div><!--/ .navigation -->

            </div>
          </nav>

app/views/shared/_partial_hero.html.erb
<div class="hero" style="">
	<div class="container">
		<h1 class="hero--header">Hire a great Photographer or Videographer</h1>
		<ul class="hero--btn list-inline">
			<li> <a href="<%= users_path %>" class="btn">Find People</a> </li>
		</ul>
	</div>
</div>

app/views/shared/_partial_hero__portfolio.html.erb
<% if @user.hero_bg.present? %>
  <div class="hero portfolio" style="background-image: url('<%= @user.hero_bg %>'); ">
<% else %>
  <div class="hero portfolio default-hero">
<% end %>
  	<div class="container">
      <div class="row">
        <div class="col-md-3 col-md-offset-2"></div>
        <div class="col-md-2">
          <% if current_user && current_user.id == @user.id %>
            <%= form_tag({controller: :users, action: :upload_avatar}, id: "upload_avatar_form", multipart: true) do %>
              <% if @user.avatar.present? %>
                <a href="" id="upload_avatar_link"><%= image_tag @user.avatar_url(:thumb), alt: "#{@user.firstname.titleize} #{@user.lastname.titleize}", id: "avatar", class: "photo center-block img-circle", style: "height:80px; width:80px" %></a>
              <% else %>
                <a href="" id="upload_avatar_link">
                  <%= image_tag "user_profiles/default.png", alt: "#{@user.firstname.titleize} #{@user.lastname.titleize}", style: "height:80px; width:80px; opacity:0.3", id: "avatar", class: "photo center-block img-circle" %> 
                </a>
              <% end %>
              <%= file_field_tag 'avatar', id: "upload_avatar", onchange: "$('#upload_avatar_form').submit();" %>
            <% end %>
          <% else %>
              <%= image_tag @user.avatar_url(:thumb), alt: "#{@user.firstname.titleize} #{@user.lastname.titleize}", id: "avatar", class: "photo center-block img-circle", style: "height:80px; width:80px" if @user.avatar.present? %>
          <% end %>     
        </div>
      </div>   
  		<h1 class="hero--header has-subheader"><%= @user.firstname.titleize %> <%= @user.lastname.titleize %></h1>
  		<h2 class="hero--subheader">
        <span><%= @user.is_photographer ? 'Photographer' : 'Client' %></span> &bull; 
        <span><%= @user.city.titleize %>, <%= @user.state %> United States</span>
      </h2>
      <% if @user.is_photographer %>
        <h2 class="hero--subheader">
          <span>$<%= @user.rate %>/hr</span> &bull; 
          <% if @user.for_hire %><span>For Hire</span> &bull; <% end %>
          <% if !@user.for_hire %><span>Not For Hire</span> &bull; <% end %>
          <% if @user.studio %><span>Has Studio</span> <% end %>
          <% if !@user.studio %><span>No Studio</span> <% end %>
        </h2>
      <% end %>
  		<div class="hero--description">
  			<p><%= @user.description %></p>
          <% if current_user && current_user.id == @user.id %>
            <%= form_tag({controller: :users, action: :upload_hero_bg}, id: "upload_hero_bg_form", multipart: true) do %>
              <a href="" id="upload_hero_bg_link"><span> <i class="fa fa-cloud-upload"></i> </span></a>
              <%= file_field_tag 'hero_bg', id: "upload_hero_bg", onchange: "$('#upload_hero_bg_form').submit();" %>
            <% end %>
          <% end %>          
  		</div>
      <% if current_user != @user %>
        <div class="row">

          <div class="col-md-3 col-md-offset-3">
            <% if current_user && current_user.id != @user.id && get_booking_status(@user, current_user) %>
              <button type="button" class="btn btn-regular btn-block" data-toggle="modal" data-target="#quoteModal">Review this photographer</button>
            <% elsif current_user && current_user.id != @user.id && !get_booking_status(@user, current_user) %>
              <a href="#" class="btn btn-regular" data-toggle="tooltip" data-placement="bottom" title="Photographer must accept your request before you can leave a review!" disabled>Review this photographer</a>
            <% elsif !current_user %>
              <a href="<%= new_user_path %>" id="review-form-toggle" class="btn btn-regular btn-block">Login to leave a review</a>
            <% end %>

          </div>
          <div class="col-md-3">
              <%= form_tag url_for(:controller => "bookings", :action => "create", :user_id => @user.id), :method => "post", class: "form-inline" do %>
                  <div class="input-group">
                    <%= text_field_tag :date, "Select Date", id: 'datepicker2', class: 'form-control address datepicker' %>
                    <div class="input-group-btn">
                    <% if current_user %>  
                      <button type="submit" id="request-photographer" class="btn btn-regular" disabled><i class="fa fa-check"></i></button>
                    <% else %>
                      <a href="#" class="btn btn-regular" data-toggle="tooltip" data-placement="bottom" title="You must be logged in to hire a photographer!" disabled><i class="fa fa-check"></i></a>
                    <% end %>
                    </div>
                  </div>
              <% end %>
              <%= content_tag "div", id: "dates_booked", data: {dates: @user.bookings.select(:id, :date_booked, :accepted_status)} do %>
              <% end %>
          </div>  
        </div>
      <% end %>
  	</div>
  </div>

<div id="portfolio-menu" class="menu">
  <div class="container">
  	 <ul class="nav navbar-nav">   
      <% if @user.is_photographer %>
    		<li><a href="<%= user_path(@user) %>"><i class="fa fa-fw fa-camera"></i> <%= pluralize(@user.photos.count, 'Shot','Shots') %></a></li>
      <% end %>
      <% if current_user && current_user.id == @user.id  && @user.is_photographer %>
    		<li><a href="<%= user_bookings_path(@user) %>"><i class="fa fa-fw fa-check"></i> <%= pluralize(user_total_bookings(@user), 'Booking','Bookings') %></a></li>
      <% end %>
      <li><a href="<%= user_reviews_path(@user) %>"><i class="fa fa-fw fa-pencil-square-o"></i> <%= pluralize(user_total_reviews(@user), 'Review','Reviews') %></a></li>
  		<li><a href="<%= user_following_path(@user) if @user %>"><i class="fa fa-fw fa-male"></i> <%= pluralize(user_total_following(@user), 'Friend', 'Friends') %></a></li>
  		<li><a href="<%= user_followers_path(@user) if @user %>"><i class="fa fa-fw fa-child"></i> <%= pluralize(user_total_followers(@user), 'Fan', 'Fans') %></a></li>
      <% if @user.is_photographer %>
        <li><a href="<%= user_projects_path(@user) %>"><i class="fa fa-fw fa-photo"></i> <%= pluralize(user_total_projects(@user), 'Project','Projects') %></a></li>
      <% end %>      
  		<% if current_user && current_user.id == @user.id  && @user.is_photographer %>
  			<li>
  				<%= link_to ' Add new project', {:controller => "projects", :action => "add_project"}, method: :post, class: "fa fa-plus" %>
				</li>
  		<% end %>

      <% if current_user && current_user != @user %>
        <% if current_user.follows.exists?(:followed_id => @user.id) %>
          <li><%= link_to " Unfollow", {:controller => "users", :action => "unfollow", :followed_id => @user.id, :follower_id => current_user.id}, method: :delete, class: "fa fa-minus" %></li>
        <% else %>
          <li><%= link_to " Follow", {:controller => "users", :action => "add_follow", :followed_id => @user.id}, method: :post, class: "fa fa-plus" %></li>
        <% end %>
      <% end %>

  	</ul>	
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="quoteModal" tabindex="-1" role="dialog" aria-labelledby="quoteModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="quoteModalLabel">Review @<%= @user.username %></h4>
      </div>
      <div class="modal-body">

        <%= form_tag(user_reviews_path(@user), :method => :post, :id => "review-form") do %>
          <div class="row">
            <div class="col-lg-12 col-md-12 col-sm-12">
              <%= text_area_tag :body, params[:body], style: "resize:vertical;", class: 'form-control', rows: 10, placeholder: 'Start typing...', :required => true %>
            </div>
          </div>
      </div>
    </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-regular" data-dismiss="modal">Close</button>
        <%= submit_tag 'Post Review', class: 'btn btn-primary' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_shots.html.erb
<div id="filterrific_results" class="shots">
	<div class="container">
		<p><%= page_entries_info @photos, :model => 'photo' %></p>
		<div class="row">
		<% @photos.each do |photo| %>
			<div class="shot-column col-sm-6 col-md-4">
				<div class="shot">
					<a href="<%= photo_path(photo) %>" class="shot-figure" style="background-image: url(<%= photo.original_url(:small) %>)">
					</a>
					<% if current_user %>
						<% if photo.likes.exists?(:user_id => current_user.id) %>
							<%= link_to '<span class="shot-heart-liked"> <i class="fa fa-heart"></i>  </span>'.html_safe, {:controller => "photos", :action => "unlike", :photo => photo.id}, method: :delete %>
						<% else %>
							<%= link_to '<span class="shot-heart"> <i class="fa fa-heart"></i>  </span>'.html_safe, {:controller => "photos", :action => "like", :photo => photo.id}, method: :post %>
						<% end %>
					<% end %>
					<div class="shot-info">

						<div class="avatar-user">
							<a class="url" rel="contact" title="" href="<%= user_path(photo.user) %>">
								<% if photo.user.avatar.present? %>
									<%= image_tag photo.user.avatar_url(:thumb), alt: "#{photo.user.firstname.titleize} #{photo.user.lastname.titleize}", id: "avatar", class: "photo" %>
								<% else %>	
									<span class="circle"><span><%= photo.user.firstname[0].upcase %></span></span>
								<% end %>
								<%= photo.user.firstname.titleize %> <%= photo.user.lastname.titleize %>
								<small class="avatar-meta block">
									<%= photo.user.city.titleize %>, <%= photo.user.state %>
									<% if @location %>
										<small class="pull-right">
											<%= Geocoder::Calculations.distance_between(@location, [photo.user.latitude, photo.user.longitude]).round(2) %> miles
										</small>
									<% end %>									
								</small>
							</a>
						</div>

						<ul class="tools">
						  <li class="fav"> <i class="fa fa-eye"></i>
						    <a title="See fans of this screenshot" href="#"><%= photo.impressionist_count %></a>
						  </li>
						  <li class="cmnt"> <i class="fa fa-comment"></i>
						  	<%= photo.comments.count %>
						  </li>
						  <li class="views"> <i class="fa fa-heart"></i>
						  	<%= photo.likes.count %>
				  		</li>
				  		<li class="pull-right">
				  			<%= time_ago_in_words(photo.created_at) %>
				  		</li>
						</ul>

					</div>
				</div>
			</div> <!--/ .col-* -->
		<% end %>

		</div> <!--/ .row -->

		<div class="text-center">
			<%= will_paginate @photos, renderer: BootstrapPagination::Rails %>				
		</div>

	</div>
</div>

app/views/shared/_shots_follow.html.erb
<div class="shots">
	<div class="container">
	<p><%= page_entries_info @follows, :model => 'user' %></p>
		<div class="row">
		<% @follows.each do |user| %>

			<div class="shot-column col-sm-6 col-md-4">
				<div class="shot">
					<a href="<%= user.is_photographer ? user_path(user) : user_reviews_path(user) %>" class="shot-figure" style="background-image: url(<%= user.photos.count > 0 ? user.photos.first.original_url(:small) : user.hero_bg.present? ? user.hero_bg : image_url('site_assets/hero-bg-small-default.jpg') %>)">
					</a>
					<div class="shot-info">				
						<div class="avatar-user">
							<a class="url" rel="contact" title="" href="<%= user.is_photographer ? user_path(user) : user_reviews_path(user) %>">
								<% if user.avatar.present? %>
									<%= image_tag user.avatar_url(:thumb), alt: "#{user.firstname.titleize} #{user.lastname.titleize}", id: "avatar", class: "photo" %>
								<% else %>	
									<span class="circle"><span><%= user.firstname[0].upcase %></span></span>
								<% end %>
								<%= user.firstname.titleize %> <%= user.lastname.titleize %>
								<small class="avatar-meta block"><%= user.city.titleize %>, <%= user.state %> United States</small>
							</a>
						</div>

						<ul class="tools">
							<li><%= user.is_photographer ? 'Photographer' : 'Client' %></li>
							<% if current_user && is_following_page? %>
						  	<li class="pull-right">
									<%= link_to ' Unfollow', {:controller => "users", :action => "unfollow", :follower_id => current_user.id, :followed_id => user.id}, method: :delete, class: "fa fa-minus-circle" %>					
						  	</li>
					  	<% end %>
						</ul>
					</div>
				</div>
			</div> <!--/ .col-* -->
		<% end %>

		</div> <!--/ .row -->

		<div class="text-center">
			<%= will_paginate @follows, renderer: BootstrapPagination::Rails %>				
		</div>
 
	</div>
</div>	

app/views/shared/_shots_portfolio__single.html.erb
<div class="shots shot-single">
	<div class="container">

		<div class="shot-column">

			<div class="shot">
				<a target="_blank" href="<%= photo_fullsize_path(@photo) %>" data-toggle="tooltip" data-placement="bottom" title="See Full Pixel" class="shot-attachment"> <i class="fa fa-lg fa-paperclip"></i>  </a>
				<img src="<%= @photo.original_url(:medium) %>" alt="" class="center-block" />
			</div>

			<div class="row">

				<div class="col-sm-7">

					<div class="avatar-user">
						<div class="url" rel="contact" title="" href="portfolio">

							<% if @photo.user.avatar.present? %>
								<%= image_tag @photo.user.avatar_url(:thumb), alt: "#{@photo.user.firstname.titleize} #{@photo.user.lastname.titleize}", id: "avatar", class: "photo" %>
							<% else %>	
								<span class="circle"><span><%= @photo.user.firstname[0].upcase %></span></span>
							<% end %>			

							<% if current_user && current_user.id == @photo.user_id %>
								<a href="#" class="photo-title url" data-value="<%= @photo.title == "" || !@photo.title ? 'Enter Title' : @photo.title %>" data-type="text" data-resource="photo" data-name="title" data-url="/photos/<%= @photo.id %>" data-original-title="Enter Title"><%= @photo.title ? @photo.title : 'Enter Title' %></a>
							<% else %>
								<%= @photo.title == "" || !@photo.title ? Project.find(@photo.project_id).category : @photo.title %>
							<% end %>
							<a href="<%= user_path(@photo.user) %>" class="avatar-meta block"> <span>by</span> <%= @fullname %></a>
						</div>
					</div>


					<div class="shot-desc">

						<% if current_user && current_user.id == @photo.user_id %>
							<a href="#" class="photo-description url" data-value="<%= @photo.description == "" || !@photo.description ? 'Enter Description' : @photo.description %>" data-type="textarea" data-resource="photo" data-name="description" data-url="/photos/<%= @photo.id %>" data-inputclass="textarea-desc"><%= @photo.description ? @photo.description : 'Enter Description' %></a>
						<% else %>
							<p><%= @photo.description == "" || !@photo.description ? "No description available" : simple_format(@photo.description) %></p>
						<% end %>
					</div>

				</div>

				<div class="col-sm-4 col-sm-offset-1">
					<ul class="shot-tools">
					  <li class="fav"> 
					    <span title="See fans of this screenshot" href="#"><i class="fa fa-eye"></i> <%= pluralize(@photo.impressionist_count, 'view', 'views') %> </span>
					  </li>
					  <li class="cmnt">  
					    <a title="View comments on this screenshot" href="#comments" class="target"> <i class="fa fa-comment"></i> <%= pluralize(@photo.comments.count, 'comment', 'comments') %></a>
					  </li>
					  <li class="views">
					  	<% if current_user %>
					  		<% if @photo.likes.exists?(:user_id => current_user.id) %>
					  			<span title="View likes on this screenshot"><%= link_to '<i class="fa fa-heart"></i>'.html_safe, {:controller => "photos", :action => "unlike", :photo => @photo.id}, method: :delete, class: "single-photo-likes" %><%= pluralize(@photo.likes.count, 'like', 'likes') %> </span>
				  			<% else %>
					  			<span title="View likes on this screenshot"><%= link_to '<i class="fa fa-heart"></i>'.html_safe, {:controller => "photos", :action => "like", :photo => @photo.id}, method: :post, class: "single-photo-likes" %><%= pluralize(@photo.likes.count, 'like', 'likes') %> </span>
				  			<% end %>
				  		<% else %>
				  			<span title="View likes on this screenshot" href="#"><i class="fa fa-heart"></i><%= pluralize(@photo.likes.count, 'like', 'likes') %></span>
				  		<% end %>
					  </li>
					</ul>

				</div>

			</div>

			<div class="row">

				<div class="col-sm-7">

				<ul id="comments" class="shot-section shot-comments">
					<label><%= pluralize(@photo.comments.count, 'Comment','Comments') %></label>
					<% @photo.comments.each do |comment| %>
					<li>
						<a class="url" rel="contact" title="" href="<%= comment.user.is_photographer ? user_path(comment.user) : user_reviews_path(comment.user) %>">
							<% if comment.user.avatar.present? %>
								<%= image_tag comment.user.avatar_url(:thumb), alt: "#{comment.user.firstname.titleize} #{comment.user.lastname.titleize}", id: "avatar", class: "photo" %>
							<% else %>	
								<span class="circle"><span><%= comment.user.firstname[0].upcase %></span></span>
							<% end %>	
							<span class="name"><%= comment.user.firstname.titleize %> <%= comment.user.lastname.titleize %></span>
						</a>	
						<div class="comment-body">
							<p><%= simple_format(comment.comment) %></p>
						</div>

						<div class="comment-meta">
							<p><%= time_ago_in_words(comment.created_at) %></p>
						</div>
					</li>
					<% end %>

				</ul>
				<% if current_user %>
					<%= form_for [@photo, Comment.new] do |f| %>
					<div class="shot-section shot-form">
						<label>Add a new comment</label>
						<div class="form-group">
							<%= f.text_area :comment, placeholder: "What do you want to say?", class: "form-control", rows: "3" %>
						</div>
						<%= f.submit "Post Comment", class: "btn btn-primary" %>
					</div>
					<% end %>
				<% end %>
				</div>


				<div class="col-sm-4 col-sm-offset-1">
					<div class="shot-section shot-next-post">
						<label><%= pluralize(@photos.count, 'Related Shot', 'Related Shots') %></label>

						<% if @first %>
							<div class="shot-figure-holder">
								<a href="<%= photo_path(@first) %>" class="shot-figure" style="background-image: url(<%= @first.original_url(:small) %>)"></a>
							</div>
						<% end %>
						
						<% if @second %>
							<div class="shot-figure-holder">
								<a href="<%= photo_path(@second) %>" class="shot-figure" style="background-image: url(<%= @second.original_url(:small) %>)"></a>
							</div>
						<% end %>

					</div>
				</div>

			</div>

		</div>

	</div>
</div>	