config/routes.rb
Rails.application.routes.draw do

  get 'home/meetups'

  get 'home/jobs'

  get 'home/about'

  get 'home/contests'

  get 'home/blog'

  resources :users do
    get 'following' => 'users#following'
    get 'followers' => 'users#followers'
    get 'analytics' => 'users#analytics'
    get 'activity' => 'users#activity'
    post 'get_quote' => 'mail#get_quote'
    resources :projects, :except => [:new]
    resources :reviews, :only => [:index, :create]
    resources :replies, :only => [:create, :update]
    resources :bookings, :only => [:index, :create, :update]
  end

  resources :photos do
    get 'fullsize' => 'photos#fullsize'
    resources :comments, :only => [:create]
  end

  resources :photo_contents, :only => [:create]
  resources :search, :only => [:index]

  put '/users/:user_id/replies/:id', :to => 'replies#update', :as => 'update_reply'
  put '/users/:id/bookings', :to => 'bookings#update', :as => 'update_booking'
  post '/upload_avatar' => 'users#upload_avatar'
  post '/upload_hero_bg' => 'users#upload_hero_bg'
  post '/add_project' => 'projects#add_project'
  post '/add_follow' => 'users#add_follow'
  delete '/unfollow' => 'users#unfollow'
  post '/like' => 'photos#like'
  delete '/unlike' => 'photos#unlike'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  
  root :to =>'photos#index'

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	require 'will_paginate'
  before_action :require_user, only: :create

  def index
  	@user = User.friendly.find(params[:user_id])
  	@reviews = @user.reviews.count > 0 ? @user.reviews.order(:created_at => :desc).group_by { |review| review.reviewed_id } : []
    @title = "#{@user.firstname.titleize} #{@user.lastname.titleize} - Photographer Reviews"
    @description = @user.description.truncate(150)
    @og_image = @user.avatar.present? ? request.base_url + @user.avatar_url : request.base_url + '/assets/user_profiles/default.png'
    @replies = @user.replies
  end

  def create
    @user = User.friendly.find(params[:user_id])
    if @user.id != current_user.id
	    Review.create(:user_id => @user.id, :reviewed_id => current_user.id, :body => params[:body])
      Activity.create(:user_id => @user.id, :activity_type => 'review', :from => current_user.id)
	    redirect_to user_reviews_path(@user)
    end
  end

end

app/views/reviews/index.html.erb
<%= render "shared/nav" %>
<%= render "shared/partial_hero__portfolio" %>
<div class="container">
	<div class="shots shot-single">
		<div class="row">
			<div class="col-sm-7">
				<div class="container" id="container-reviews">
					<% @reviews.each do |group| %>
							<div class="container" style="padding-top:10px">
								<div class="row reviews-wrap">
									<div class="col-sm-5">
										<div class="shot shot-reviewer">
												<a href="<%= User.find(group[0]).is_photographer ? user_path(group[0]) : user_reviews_path(group[0]) %>" class="shot-figure" style="background-image: url(<%= User.find(group[0]).photos.count > 0 ? User.find(group[0]).photos.first.original_url(:small) : User.find(group[0]).hero_bg.present? ? User.find(group[0]).hero_bg : image_url("site_assets/hero-bg-small-default.jpg") %>)"></a>
											<div class="shot-info">

												<div class="avatar-user">
													<a class="url" rel="contact" title="" href="<%= user_path(group[0]) %>">
														<% if User.find(group[0]).avatar.present? %>
															<%= image_tag User.find(group[0]).avatar_url(:thumb), alt: "#{User.find(group[0]).firstname.titleize} #{User.find(group[0]).lastname.titleize}", id: "avatar", class: "photo" %>
														<% else %>	
															<span class="circle"><span><%= User.find(group[0]).firstname[0].upcase %></span></span>
														<% end %>
														<%= User.find(group[0]).firstname.titleize %> <%= User.find(group[0]).lastname.titleize %>
														<small class="avatar-meta block">
															<%= User.find(group[0]).city.titleize %>, <%= User.find(group[0]).state %>
														</small>
													</a>
												</div>

												<ul class="tools">
												  <li class="fav"> <i class="fa fa-eye"></i> 
												    <a title="See fans of this photographer" href="#"><%= get_user_total_views(User.find(group[0])) %></a>
												  </li>
												  <li class="cmnt"> <i class="fa fa-comment"></i> 
												    <a title="View comments of this photographer" href="#"><%= get_user_total_comments(User.find(group[0])) %></a>
												  </li>
												  <li class="views"> <i class="fa fa-heart"></i> 
												  	<a title="View likes of this photographer" href="#"><%= get_user_total_likes(User.find(group[0])) %> </a>
											  	</li>
												  <li class="views"> <i class="fa fa-fw fa-child"></i> 
												  	<a title="View followers of this photographer" href="#"><%= User.find(group[0]).followers.count %> </a>
											  	</li>					  	
													<li class="pull-right">
														<%= User.find(group[0]).is_photographer ? 'Photographer' : 'Client' %>
													</li>
												</ul>

											</div>
										</div>									
									</div>
									<div class="col-sm-7 review-text">
										<% group[1].each_with_index do |review, i| %>
											<span><%= review.created_at.strftime("%m/%d/%Y") %></span>
											<%= i == 0 ? '<span class="label label-success">Updated Review</span>'.html_safe : '<span class="label label-default">Previous Review</span>'.html_safe %>
											<br><br>
											<div class="panel panel-default">
											  <div class="panel-body">
											    <%= textarea_format(review.body) %>
											  </div>
											</div>

											<% reply = Reply.where(:user_id => @user.id).where(:reviewer_id => review.reviewed_id) %>
											<% if reply.exists? %>

												<!-- Reviews are in order, if next reviewed_id does not match then it is a reply -->
												<!-- Display reply when this condition is met -->
												<% if i == group[1].length-1 %>
													<div class="well">
														<a class="url" rel="contact" title="" href="<%= user_reviews_path(@user) %>">
															<% if @user.avatar.present? %>
																	<%= image_tag @user.avatar_url(:thumb), alt: "#{@user.firstname.titleize} #{@user.lastname.titleize}", id: "avatar", class: "img-circle", :style => 'width:48px; height:48px;' %>
																<% else %>	
																	<div class="avatar-review">
					                          <%= image_tag("user_profiles/default-avatar.jpg", alt: "avatar", :class => "img-circle") %>
					                          <p class="avatar-text-review"><%= @user.firstname[0].upcase %></p>
					                        </div>
																<% end %>
														</a>
														<span class="review-text">Comment from <%= @user.firstname.titleize %> <%= @user.lastname.titleize %></span>
														<span class="label label-primary">Owner</span>
														<div class="review-body">
															<p class="review-text"><%= textarea_format(reply[0].body) %></p>
														</div>

														<div class="review-meta">
															<p class="review-text" style="display:inline-block"><%= time_ago_in_words(reply[0].updated_at) %> ago</p>

															<% if current_user && current_user.id == @user.id %>

																<button class="reply-form-toggle" style="font-size:12px"><i class="fa fa-pencil"></i> Edit this reply</button>

																<%= form_tag(user_reply_path(current_user.id, reply[0].id), :method => :put, :class => "reply-form") do %>
																	<div class="form-group">
																		<%= text_area_tag :body, reply[0].body, :style => "width: 100%;", rows: "5", tabindex: "1", class: "form-control" %>
																	</div>
																	<div class="form-group">
																		<%= submit_tag "Submit", id:"reply-submit", tabindex:"4", class:"btn btn-primary" %>
																	</div>
																<% end %>										
										          <% end %>

														</div>

													</div>
												<% end %>
											<% else %>
								        <div class="shot-section shot-form">
								        	<% if i == 0 && current_user && current_user.id == @user.id %>

								        			<button class="reply-form-toggle" style="font-size:12px"><i class="fa fa-pencil"></i> Reply to this person</button>

										          <%= form_tag(user_replies_path(current_user.id), :method => :post, :class => "reply-form") do %>
										          	<%= hidden_field_tag 'reviewer_id', review.reviewed_id %>
										            <div class="form-group">
										              <%= text_area_tag :body, params[:body], class: 'form-control', rows: "5", placeholder: "Enter Reply" %>
									              </div>
										              <%= button_tag 'Post Reply', name: nil, class: "btn btn-primary" %>
										          <% end %> 

								          <% end %>
								        </div>
											<% end %>

										<% end %>							
									</div>
								</div>
							</div>
						<% end %>
				</div>

			</div>
		</div>
	</div>
</div>